### ISSUE TITLE
`fail-on-warnings` does not actually work

### ISSUE THREAD

**Issue by tk-nguyen** [zgosalvez/github-actions-analyze-dart#14]
Hello, we're currently using this action in our workflow. The `fail-on-warnings` option is set to `false`, but the step fails anyway, because `dart analyze --format machine .` has exit code 2 when there are warnings. Maybe this is an oversight?

Here are the screenshots:

![image](https://user-images.githubusercontent.com/39090621/193220023-ddee1961-7c56-42ad-9e20-25b07c7354d0.png)

![image](https://user-images.githubusercontent.com/39090621/193220105-aef974cc-9323-4049-bc5c-646b9dbc1c57.png)

**Comment by zgosalvez** [comment]
Hi. Exit codes are considered errors, so the action will fail regardless of the `fail-on-warnings` setting.

**Comment by zgosalvez** [comment]
@jake-wickstrom, exit codes occur for different scenarios. I recommend running `dart analyze` on your local environment to debug. Usually, this is caused by a minor misconfiguration.
